// <auto-generated />
namespace Rival.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class playerdashboard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(playerdashboard));
        
        string IMigrationMetadata.Id
        {
            get { return "202111141645171_playerdashboard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
